HOST: http://localhost

--- Note API V0.2 ---
---
Welcome to the our Note API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

API-Version: 0.2

-- 
User Resources 
Everthing you need to retrieve a user token.

-- 
Creates a new user.
POST /api/{api-version}/user
{ "username": "mustermann", "password": "secret"}
< 200
< Content-Type: application/json
{ "token": "dfsgrg-456456dfgf-45646"}

Retrieve a user token
GET /api/{api-version}/user/{username}/{password}
< 200
< Content-Type: application/json
{ "token": "dfsgrg-456456dfgf-45646"}


--
Note Resources
The following is a section of resources related o the notes.

Authentifiaktion will be handled later

--
Save a new note.
POST /api/{api-version}/user/{username}/note
> Content-Type: application/json
{ "text": "My first note ...", "type": "text-note"}
< 200
< Content-Type: application/json
{ "status": "created", "url": "/api/note/23456363"}


Edit a note.
PUT /api/{api-version}/user/{username}/note/{id}
> Content-Type: application/json
< 200
< Content-Type: application/json
{ "text": "My first note ith changes", "type": "text-note"}


Delete a note.
DELETE /api/{api-version}/user/{username}/note/{id}
> Content-Type: application/json
< 200
< Content-Type: application/json


List all notes for the user.

* *query* - A query to select only some notes by an equal criteria.
* *sort* - Defining an order.
* *fields* - Limit the transfered fields to minimize the payload.

GET /api/{api-version}/user/{username}/note/{?query, sort, fields}
< 200
< Content-Type: application/json
{ "items": [
{ "text": "My first note ...", "created_at":"2013-04-02 19:00", "type": "text-note"}
] }





